//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FE.Creator.CipherMachine.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CipherLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CipherLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FE.Creator.CipherMachine.Lang.CipherLang", typeof(CipherLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt content error.
        /// </summary>
        internal static string APP_DECRYPT_ERROR {
            get {
                return ResourceManager.GetString("APP_DECRYPT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt content error.
        /// </summary>
        internal static string APP_ENCRYPT_ERROR {
            get {
                return ResourceManager.GetString("APP_ENCRYPT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Initialize the Application.
        /// </summary>
        internal static string APP_INITIALIZE_FAILED {
            get {
                return ResourceManager.GetString("APP_INITIALIZE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing the application....
        /// </summary>
        internal static string APP_INITIALIZING {
            get {
                return ResourceManager.GetString("APP_INITIALIZING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input string is not valid.
        /// </summary>
        internal static string APP_INPUT_TEXT_INVALID {
            get {
                return ResourceManager.GetString("APP_INPUT_TEXT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Success!.
        /// </summary>
        internal static string APP_LOAD_SUCCESS {
            get {
                return ResourceManager.GetString("APP_LOAD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Copied to Clipboard!.
        /// </summary>
        internal static string APP_RESULT_COPIED {
            get {
                return ResourceManager.GetString("APP_RESULT_COPIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cipher Machine V1.0.
        /// </summary>
        internal static string APP_VERSION {
            get {
                return ResourceManager.GetString("APP_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Result.
        /// </summary>
        internal static string BTN_COPY {
            get {
                return ResourceManager.GetString("BTN_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt.
        /// </summary>
        internal static string BTN_DECRYPT {
            get {
                return ResourceManager.GetString("BTN_DECRYPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt.
        /// </summary>
        internal static string BTN_ENCRYPT {
            get {
                return ResourceManager.GetString("BTN_ENCRYPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input the Text to be Encrypted/Decripted.
        /// </summary>
        internal static string LBL_INPUT_STRING {
            get {
                return ResourceManager.GetString("LBL_INPUT_STRING", resourceCulture);
            }
        }
    }
}
