//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FE.Creator.Admin.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FE.Creator.Admin.lang.AppLang", typeof(AppLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        public static string ACCOUNTMGR_ATTENTION {
            get {
                return ResourceManager.GetString("ACCOUNTMGR_ATTENTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Crypotography Tool.
        /// </summary>
        public static string ACCOUNTMGR_BTN_DOWLOAD_TOOL {
            get {
                return ResourceManager.GetString("ACCOUNTMGR_BTN_DOWLOAD_TOOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Record.
        /// </summary>
        public static string ACCOUNTMGR_BTN_NEWREC {
            get {
                return ResourceManager.GetString("ACCOUNTMGR_BTN_NEWREC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Even through account senstive data were encrypted by system, but we recommand you to download a cryptography tool to encrypt your sensitive data before save them to the system..
        /// </summary>
        public static string ACCOUNTMGR_ENCTOOL_DESC {
            get {
                return ResourceManager.GetString("ACCOUNTMGR_ENCTOOL_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Type.
        /// </summary>
        public static string ACCOUNTMGR_LBL_ACTTYPE {
            get {
                return ResourceManager.GetString("ACCOUNTMGR_LBL_ACTTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ACCOUNTMGR_LBL_DESC {
            get {
                return ResourceManager.GetString("ACCOUNTMGR_LBL_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No./Login.
        /// </summary>
        public static string ACCOUNTMGR_LBL_LOGIN {
            get {
                return ResourceManager.GetString("ACCOUNTMGR_LBL_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string ACCOUNTMGR_LBL_PASS {
            get {
                return ResourceManager.GetString("ACCOUNTMGR_LBL_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Title.
        /// </summary>
        public static string ACCOUNTMGR_LBL_TITLE {
            get {
                return ResourceManager.GetString("ACCOUNTMGR_LBL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        public static string ACCOUNTMGR_RDO_BANK {
            get {
                return ResourceManager.GetString("ACCOUNTMGR_RDO_BANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string ACCOUNTMGR_RDO_DEVICES {
            get {
                return ResourceManager.GetString("ACCOUNTMGR_RDO_DEVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet.
        /// </summary>
        public static string ACCOUNTMGR_RDO_INTERNET {
            get {
                return ResourceManager.GetString("ACCOUNTMGR_RDO_INTERNET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string ACCOUNTMGR_TH_ACTION {
            get {
                return ResourceManager.GetString("ACCOUNTMGR_TH_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ACCOUNTMGR_TH_DESC {
            get {
                return ResourceManager.GetString("ACCOUNTMGR_TH_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No./Name.
        /// </summary>
        public static string ACCOUNTMGR_TH_NAME {
            get {
                return ResourceManager.GetString("ACCOUNTMGR_TH_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string ACCOUNTMGR_TH_PASS {
            get {
                return ResourceManager.GetString("ACCOUNTMGR_TH_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Title.
        /// </summary>
        public static string ACCOUNTMGR_TH_TITLE {
            get {
                return ResourceManager.GetString("ACCOUNTMGR_TH_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Management.
        /// </summary>
        public static string ACCOUNTMGR_TITLE {
            get {
                return ResourceManager.GetString("ACCOUNTMGR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +Book.
        /// </summary>
        public static string BOOK_ADD_BOOK {
            get {
                return ResourceManager.GetString("BOOK_ADD_BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Books.
        /// </summary>
        public static string BOOK_ALL_BOOKS {
            get {
                return ResourceManager.GetString("BOOK_ALL_BOOKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Gallary.
        /// </summary>
        public static string BOOK_BOOK_GALLARY {
            get {
                return ResourceManager.GetString("BOOK_BOOK_GALLARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string BOOK_BTN_CANCEL {
            get {
                return ResourceManager.GetString("BOOK_BTN_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string BOOK_BTN_SAVE {
            get {
                return ResourceManager.GetString("BOOK_BTN_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload book.
        /// </summary>
        public static string BOOK_BTN_UPLOAD {
            get {
                return ResourceManager.GetString("BOOK_BTN_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string BOOK_FIELD_AUTHOR {
            get {
                return ResourceManager.GetString("BOOK_FIELD_AUTHOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        public static string BOOK_FIELD_INTRODUCTION {
            get {
                return ResourceManager.GetString("BOOK_FIELD_INTRODUCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN.
        /// </summary>
        public static string BOOK_FIELD_ISBN {
            get {
                return ResourceManager.GetString("BOOK_FIELD_ISBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Name.
        /// </summary>
        public static string BOOK_FIELD_NAME {
            get {
                return ResourceManager.GetString("BOOK_FIELD_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared.
        /// </summary>
        public static string BOOK_FIELD_SHARED {
            get {
                return ResourceManager.GetString("BOOK_FIELD_SHARED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string BOOK_FIELD_VERSION {
            get {
                return ResourceManager.GetString("BOOK_FIELD_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string BOOK_RDO_PRIVATE {
            get {
                return ResourceManager.GetString("BOOK_RDO_PRIVATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared.
        /// </summary>
        public static string BOOK_RDO_SHARED {
            get {
                return ResourceManager.GetString("BOOK_RDO_SHARED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search books....
        /// </summary>
        public static string BOOK_SEARCH_PLH {
            get {
                return ResourceManager.GetString("BOOK_SEARCH_PLH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books Management.
        /// </summary>
        public static string BOOK_TITLE {
            get {
                return ResourceManager.GetString("BOOK_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string COMMON_BTN_CANCEL {
            get {
                return ResourceManager.GetString("COMMON_BTN_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string COMMON_BTN_CONFIRM {
            get {
                return ResourceManager.GetString("COMMON_BTN_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string COMMON_BTN_DELETE {
            get {
                return ResourceManager.GetString("COMMON_BTN_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string COMMON_BTN_EDIT {
            get {
                return ResourceManager.GetString("COMMON_BTN_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string COMMON_BTN_PREVIEW {
            get {
                return ResourceManager.GetString("COMMON_BTN_PREVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string COMMON_BTN_SAVE {
            get {
                return ResourceManager.GetString("COMMON_BTN_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Dropdown.
        /// </summary>
        public static string COMMON_OPT_TOGGLE_DOWN {
            get {
                return ResourceManager.GetString("COMMON_OPT_TOGGLE_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Contact.
        /// </summary>
        public static string CONTACTS_BTN_NEWCONTACT {
            get {
                return ResourceManager.GetString("CONTACTS_BTN_NEWCONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to List.
        /// </summary>
        public static string CONTACTS_BTN_RETURNTOLIST {
            get {
                return ResourceManager.GetString("CONTACTS_BTN_RETURNTOLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string CONTACTS_COL_ACTION {
            get {
                return ResourceManager.GetString("CONTACTS_COL_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Frequency.
        /// </summary>
        public static string CONTACTS_COL_FREQUENCY {
            get {
                return ResourceManager.GetString("CONTACTS_COL_FREQUENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Phone.
        /// </summary>
        public static string CONTACTS_COL_PHONE {
            get {
                return ResourceManager.GetString("CONTACTS_COL_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship Note.
        /// </summary>
        public static string CONTACTS_COL_RSNOTE {
            get {
                return ResourceManager.GetString("CONTACTS_COL_RSNOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string CONTACTS_COL_USERNAME {
            get {
                return ResourceManager.GetString("CONTACTS_COL_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship.
        /// </summary>
        public static string CONTACTS_LBL_RELATIONSHIP {
            get {
                return ResourceManager.GetString("CONTACTS_LBL_RELATIONSHIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap Level.
        /// </summary>
        public static string CONTACTS_LBL_TAPLEVEL {
            get {
                return ResourceManager.GetString("CONTACTS_LBL_TAPLEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string CONTACTS_SUBTITLE {
            get {
                return ResourceManager.GetString("CONTACTS_SUBTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts Management.
        /// </summary>
        public static string CONTACTS_TITLE {
            get {
                return ResourceManager.GetString("CONTACTS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author Mood.
        /// </summary>
        public static string DIARYMGR_AUTHOR_MOOD {
            get {
                return ResourceManager.GetString("DIARYMGR_AUTHOR_MOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diary.
        /// </summary>
        public static string DIARYMGR_DIARY {
            get {
                return ResourceManager.GetString("DIARYMGR_DIARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Diary.
        /// </summary>
        public static string DIARYMGR_NEW_DIARY {
            get {
                return ResourceManager.GetString("DIARYMGR_NEW_DIARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to List.
        /// </summary>
        public static string DIARYMGR_RETURN_LIST {
            get {
                return ResourceManager.GetString("DIARYMGR_RETURN_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diary Management.
        /// </summary>
        public static string DIARYMGR_TITLE {
            get {
                return ResourceManager.GetString("DIARYMGR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        public static string DIARYMGR_WEATHER {
            get {
                return ResourceManager.GetString("DIARYMGR_WEATHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +Document.
        /// </summary>
        public static string DOCUMENT_ADD_DOCUMENT {
            get {
                return ResourceManager.GetString("DOCUMENT_ADD_DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +Folder.
        /// </summary>
        public static string DOCUMENT_ADD_FOLDER {
            get {
                return ResourceManager.GetString("DOCUMENT_ADD_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DOCUMENT_BTN_CANCEL {
            get {
                return ResourceManager.GetString("DOCUMENT_BTN_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string DOCUMENT_BTN_SAVE {
            get {
                return ResourceManager.GetString("DOCUMENT_BTN_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload File.
        /// </summary>
        public static string DOCUMENT_BTN_UPLOAD {
            get {
                return ResourceManager.GetString("DOCUMENT_BTN_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Name.
        /// </summary>
        public static string DOCUMENT_EDIT_FOLDER_NAME {
            get {
                return ResourceManager.GetString("DOCUMENT_EDIT_FOLDER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid View.
        /// </summary>
        public static string DOCUMENT_GRID_VIEW {
            get {
                return ResourceManager.GetString("DOCUMENT_GRID_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string DOCUMENT_LBL_FILENAME {
            get {
                return ResourceManager.GetString("DOCUMENT_LBL_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared.
        /// </summary>
        public static string DOCUMENT_LBL_SHARED {
            get {
                return ResourceManager.GetString("DOCUMENT_LBL_SHARED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string DOCUMENT_LBL_VERSION {
            get {
                return ResourceManager.GetString("DOCUMENT_LBL_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List View.
        /// </summary>
        public static string DOCUMENT_LIST_VIEW {
            get {
                return ResourceManager.GetString("DOCUMENT_LIST_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string DOCUMENT_RDO_PRIVATE {
            get {
                return ResourceManager.GetString("DOCUMENT_RDO_PRIVATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared.
        /// </summary>
        public static string DOCUMENT_RDO_SHARED {
            get {
                return ResourceManager.GetString("DOCUMENT_RDO_SHARED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Documents.
        /// </summary>
        public static string DOCUMENT_SEARCH_TEXT_PLH {
            get {
                return ResourceManager.GetString("DOCUMENT_SEARCH_TEXT_PLH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string DOCUMENT_TH_ACTION {
            get {
                return ResourceManager.GetString("DOCUMENT_TH_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        public static string DOCUMENT_TH_MODIFIED {
            get {
                return ResourceManager.GetString("DOCUMENT_TH_MODIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DOCUMENT_TH_NAME {
            get {
                return ResourceManager.GetString("DOCUMENT_TH_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string DOCUMENT_TH_OWNER {
            get {
                return ResourceManager.GetString("DOCUMENT_TH_OWNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size (KB).
        /// </summary>
        public static string DOCUMENT_TH_SIZE_KB {
            get {
                return ResourceManager.GetString("DOCUMENT_TH_SIZE_KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Management.
        /// </summary>
        public static string DOCUMENT_TITLE {
            get {
                return ResourceManager.GetString("DOCUMENT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        public static string IMAGEMGR_ALBUM {
            get {
                return ResourceManager.GetString("IMAGEMGR_ALBUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alburms.
        /// </summary>
        public static string IMAGEMGR_ALBUMS {
            get {
                return ResourceManager.GetString("IMAGEMGR_ALBUMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Image.
        /// </summary>
        public static string IMAGEMGR_BTN_UPLOADIMG {
            get {
                return ResourceManager.GetString("IMAGEMGR_BTN_UPLOADIMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert!.
        /// </summary>
        public static string IMAGEMGR_ERR_ALERT {
            get {
                return ResourceManager.GetString("IMAGEMGR_ERR_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string IMAGEMGR_IMAGES {
            get {
                return ResourceManager.GetString("IMAGEMGR_IMAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string IMAGEMGR_LBL_DESC {
            get {
                return ResourceManager.GetString("IMAGEMGR_LBL_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Title.
        /// </summary>
        public static string IMAGEMGR_LBL_IMGTITLE {
            get {
                return ResourceManager.GetString("IMAGEMGR_LBL_IMGTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to album Name.
        /// </summary>
        public static string IMAGEMGR_LBL_NAME {
            get {
                return ResourceManager.GetString("IMAGEMGR_LBL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared.
        /// </summary>
        public static string IMAGEMGR_LBL_SHARED {
            get {
                return ResourceManager.GetString("IMAGEMGR_LBL_SHARED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to album Type.
        /// </summary>
        public static string IMAGEMGR_LBL_TYPE {
            get {
                return ResourceManager.GetString("IMAGEMGR_LBL_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string IMAGEMGR_RDO_PRIVATE {
            get {
                return ResourceManager.GetString("IMAGEMGR_RDO_PRIVATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared.
        /// </summary>
        public static string IMAGEMGR_RDO_SHARED {
            get {
                return ResourceManager.GetString("IMAGEMGR_RDO_SHARED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos Management.
        /// </summary>
        public static string IMAGEMGR_TITLE {
            get {
                return ResourceManager.GetString("IMAGEMGR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View More Images.
        /// </summary>
        public static string IMAGEMGR_VIEW_MORE_IMGS {
            get {
                return ResourceManager.GetString("IMAGEMGR_VIEW_MORE_IMGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string INDEX_REPORT_BOOKS {
            get {
                return ResourceManager.GetString("INDEX_REPORT_BOOKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string INDEX_REPORT_COL_AUTHOR {
            get {
                return ResourceManager.GetString("INDEX_REPORT_COL_AUTHOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string INDEX_REPORT_COL_DATE {
            get {
                return ResourceManager.GetString("INDEX_REPORT_COL_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string INDEX_REPORT_COL_TITLE {
            get {
                return ResourceManager.GetString("INDEX_REPORT_COL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string INDEX_REPORT_COL_VERSION {
            get {
                return ResourceManager.GetString("INDEX_REPORT_COL_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Images.
        /// </summary>
        public static string INDEX_REPORT_LATEST_IMAGES {
            get {
                return ResourceManager.GetString("INDEX_REPORT_LATEST_IMAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts.
        /// </summary>
        public static string INDEX_REPORT_POSTS {
            get {
                return ResourceManager.GetString("INDEX_REPORT_POSTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All Books.
        /// </summary>
        public static string INDEX_REPORT_VIEW_ALLBOOKS {
            get {
                return ResourceManager.GetString("INDEX_REPORT_VIEW_ALLBOOKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All Images.
        /// </summary>
        public static string INDEX_REPORT_VIEW_ALLIMGS {
            get {
                return ResourceManager.GetString("INDEX_REPORT_VIEW_ALLIMGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All Posts.
        /// </summary>
        public static string INDEX_REPORT_VIEW_ALLPOSTS {
            get {
                return ResourceManager.GetString("INDEX_REPORT_VIEW_ALLPOSTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL BOOKS.
        /// </summary>
        public static string INDEX_TOTAL_BOOKS {
            get {
                return ResourceManager.GetString("INDEX_TOTAL_BOOKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL CONTACTS.
        /// </summary>
        public static string INDEX_TOTAL_CONTACTS {
            get {
                return ResourceManager.GetString("INDEX_TOTAL_CONTACTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL IMAGES.
        /// </summary>
        public static string INDEX_TOTAL_IMAGES {
            get {
                return ResourceManager.GetString("INDEX_TOTAL_IMAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL POSTS.
        /// </summary>
        public static string INDEX_TOTAL_POSTS {
            get {
                return ResourceManager.GetString("INDEX_TOTAL_POSTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Console.
        /// </summary>
        public static string LAYOUT_ADMIN_CONSOLE {
            get {
                return ResourceManager.GetString("LAYOUT_ADMIN_CONSOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FE Contributes Space.
        /// </summary>
        public static string LAYOUT_COMPANY {
            get {
                return ResourceManager.GetString("LAYOUT_COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console.
        /// </summary>
        public static string LAYOUT_CONSOLE {
            get {
                return ResourceManager.GetString("LAYOUT_CONSOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright &amp;copy; 2016.
        /// </summary>
        public static string LAYOUT_COPYRIGHT {
            get {
                return ResourceManager.GetString("LAYOUT_COPYRIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved..
        /// </summary>
        public static string LAYOUT_COPYRIGHT_STR {
            get {
                return ResourceManager.GetString("LAYOUT_COPYRIGHT_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Management.
        /// </summary>
        public static string LAYOUT_NAV_ACTMGR {
            get {
                return ResourceManager.GetString("LAYOUT_NAV_ACTMGR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string LAYOUT_NAV_BOOKS {
            get {
                return ResourceManager.GetString("LAYOUT_NAV_BOOKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string LAYOUT_NAV_CONTACTS {
            get {
                return ResourceManager.GetString("LAYOUT_NAV_CONTACTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Management.
        /// </summary>
        public static string LAYOUT_NAV_DATAMGR {
            get {
                return ResourceManager.GetString("LAYOUT_NAV_DATAMGR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diary.
        /// </summary>
        public static string LAYOUT_NAV_DIARY {
            get {
                return ResourceManager.GetString("LAYOUT_NAV_DIARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string LAYOUT_NAV_DOCUMENTS {
            get {
                return ResourceManager.GetString("LAYOUT_NAV_DOCUMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efficiency.
        /// </summary>
        public static string LAYOUT_NAV_EFFICIENCY {
            get {
                return ResourceManager.GetString("LAYOUT_NAV_EFFICIENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Objects.
        /// </summary>
        public static string LAYOUT_NAV_GENERALOBJ {
            get {
                return ResourceManager.GetString("LAYOUT_NAV_GENERALOBJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Management.
        /// </summary>
        public static string LAYOUT_NAV_LICENSE {
            get {
                return ResourceManager.GetString("LAYOUT_NAV_LICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAIN NAVIGATION.
        /// </summary>
        public static string LAYOUT_NAV_MAIN {
            get {
                return ResourceManager.GetString("LAYOUT_NAV_MAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        public static string LAYOUT_NAV_PHOTOS {
            get {
                return ResourceManager.GetString("LAYOUT_NAV_PHOTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts.
        /// </summary>
        public static string LAYOUT_NAV_POSTS {
            get {
                return ResourceManager.GetString("LAYOUT_NAV_POSTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Configuraion.
        /// </summary>
        public static string LAYOUT_NAV_SYSCONF {
            get {
                return ResourceManager.GetString("LAYOUT_NAV_SYSCONF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Users.
        /// </summary>
        public static string LAYOUT_NAV_SYSUSR {
            get {
                return ResourceManager.GetString("LAYOUT_NAV_SYSUSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Management.
        /// </summary>
        public static string LAYOUT_NAV_TASKMGR {
            get {
                return ResourceManager.GetString("LAYOUT_NAV_TASKMGR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle navigation.
        /// </summary>
        public static string LAYOUT_NAV_TOGGLE {
            get {
                return ResourceManager.GetString("LAYOUT_NAV_TOGGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        public static string LAYOUT_NAV_USRMGR {
            get {
                return ResourceManager.GetString("LAYOUT_NAV_USRMGR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string LAYOUT_PROFILE {
            get {
                return ResourceManager.GetString("LAYOUT_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string LAYOUT_SIGNOUT {
            get {
                return ResourceManager.GetString("LAYOUT_SIGNOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string LAYOUT_STATUS_ONLINE {
            get {
                return ResourceManager.GetString("LAYOUT_STATUS_ONLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just for the Best Experience!.
        /// </summary>
        public static string LAYOUT_SUBTITLE {
            get {
                return ResourceManager.GetString("LAYOUT_SUBTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string LAYOUT_VERSION {
            get {
                return ResourceManager.GetString("LAYOUT_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Group.
        /// </summary>
        public static string POST_ADD_GROUP {
            get {
                return ResourceManager.GetString("POST_ADD_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Posts.
        /// </summary>
        public static string POST_ALL_POSTS {
            get {
                return ResourceManager.GetString("POST_ALL_POSTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string POST_BTN_DELETE {
            get {
                return ResourceManager.GetString("POST_BTN_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string POST_BTN_EDIT {
            get {
                return ResourceManager.GetString("POST_BTN_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string POST_BTN_PRINT {
            get {
                return ResourceManager.GetString("POST_BTN_PRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to List.
        /// </summary>
        public static string POST_BTN_RETURN_TO_LIST {
            get {
                return ResourceManager.GetString("POST_BTN_RETURN_TO_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Post Image.
        /// </summary>
        public static string POST_BTN_UPLOAD_IMG {
            get {
                return ResourceManager.GetString("POST_BTN_UPLOAD_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string POST_BTN_VIEW {
            get {
                return ResourceManager.GetString("POST_BTN_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Group.
        /// </summary>
        public static string POST_DELETE_GROUP {
            get {
                return ResourceManager.GetString("POST_DELETE_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Group.
        /// </summary>
        public static string POST_EDIT_GROUP {
            get {
                return ResourceManager.GetString("POST_EDIT_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string POST_LBL_CONTENT {
            get {
                return ResourceManager.GetString("POST_LBL_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        public static string POST_LBL_INTRODUCTION {
            get {
                return ResourceManager.GetString("POST_LBL_INTRODUCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Original.
        /// </summary>
        public static string POST_LBL_ISORIGINAL {
            get {
                return ResourceManager.GetString("POST_LBL_ISORIGINAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original.
        /// </summary>
        public static string POST_LBL_ORIGINAL {
            get {
                return ResourceManager.GetString("POST_LBL_ORIGINAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared.
        /// </summary>
        public static string POST_LBL_SHARED {
            get {
                return ResourceManager.GetString("POST_LBL_SHARED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string POST_LBL_TITLE {
            get {
                return ResourceManager.GetString("POST_LBL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Post.
        /// </summary>
        public static string POST_NEW_POST {
            get {
                return ResourceManager.GetString("POST_NEW_POST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string POST_RDO_NO {
            get {
                return ResourceManager.GetString("POST_RDO_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string POST_RDO_PRIVATE {
            get {
                return ResourceManager.GetString("POST_RDO_PRIVATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared.
        /// </summary>
        public static string POST_RDO_SHARED {
            get {
                return ResourceManager.GetString("POST_RDO_SHARED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string POST_RDO_YES {
            get {
                return ResourceManager.GetString("POST_RDO_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Management.
        /// </summary>
        public static string POST_TITLE {
            get {
                return ResourceManager.GetString("POST_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Date.
        /// </summary>
        public static string TASKMGR_LBL_COMP_DATE {
            get {
                return ResourceManager.GetString("TASKMGR_LBL_COMP_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string TASKMGR_LBL_DESC {
            get {
                return ResourceManager.GetString("TASKMGR_LBL_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string TASKMGR_LBL_ENDDATE {
            get {
                return ResourceManager.GetString("TASKMGR_LBL_ENDDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string TASKMGR_LBL_STARTDATE {
            get {
                return ResourceManager.GetString("TASKMGR_LBL_STARTDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Name.
        /// </summary>
        public static string TASKMGR_LBL_TASKNAME {
            get {
                return ResourceManager.GetString("TASKMGR_LBL_TASKNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Type.
        /// </summary>
        public static string TASKMGR_LBL_TASKTYPE {
            get {
                return ResourceManager.GetString("TASKMGR_LBL_TASKTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Title.
        /// </summary>
        public static string TASKMGR_LBL_TGTTITLE {
            get {
                return ResourceManager.GetString("TASKMGR_LBL_TGTTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Type.
        /// </summary>
        public static string TASKMGR_LBL_TGTTYPE {
            get {
                return ResourceManager.GetString("TASKMGR_LBL_TGTTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important.
        /// </summary>
        public static string TASKMGR_RDO_IMPORTANT {
            get {
                return ResourceManager.GetString("TASKMGR_RDO_IMPORTANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string TASKMGR_RDO_LOW {
            get {
                return ResourceManager.GetString("TASKMGR_RDO_LOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string TASKMGR_RDO_MEDIUM {
            get {
                return ResourceManager.GetString("TASKMGR_RDO_MEDIUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targets.
        /// </summary>
        public static string TASKMGR_TAB_TARGETS {
            get {
                return ResourceManager.GetString("TASKMGR_TAB_TARGETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string TASKMGR_TAB_TASKS {
            get {
                return ResourceManager.GetString("TASKMGR_TAB_TASKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task List.
        /// </summary>
        public static string TASKMGR_TASKLIST {
            get {
                return ResourceManager.GetString("TASKMGR_TASKLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string TASKMGR_TH_ACTION {
            get {
                return ResourceManager.GetString("TASKMGR_TH_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string TASKMGR_TH_DESC {
            get {
                return ResourceManager.GetString("TASKMGR_TH_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string TASKMGR_TH_PROGRESS {
            get {
                return ResourceManager.GetString("TASKMGR_TH_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string TASKMGR_TH_TASK {
            get {
                return ResourceManager.GetString("TASKMGR_TH_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Management.
        /// </summary>
        public static string TASKMGR_TITLE {
            get {
                return ResourceManager.GetString("TASKMGR_TITLE", resourceCulture);
            }
        }
    }
}
