//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FE.Creator.Admin.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConsolePortal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConsolePortal() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FE.Creator.Admin.lang.ConsolePortal", typeof(ConsolePortal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Your Mind.
        /// </summary>
        public static string PORTAL_BOOK_DESC {
            get {
                return ResourceManager.GetString("PORTAL_BOOK_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOK.
        /// </summary>
        public static string PORTAL_BOOK_TITLE {
            get {
                return ResourceManager.GetString("PORTAL_BOOK_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string PORTAL_FOOTER_ABOUT {
            get {
                return ResourceManager.GetString("PORTAL_FOOTER_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEConsole is a easy to use web application, it is in purpose of protecting and organizing your personal information, valuable memories, knowlege in one place!
        ///.
        /// </summary>
        public static string PORTAL_FOOTER_ABOUT_DESC {
            get {
                return ResourceManager.GetString("PORTAL_FOOTER_ABOUT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beijing, China.
        /// </summary>
        public static string PORTAL_FOOTER_CONTACT_ADDR {
            get {
                return ResourceManager.GetString("PORTAL_FOOTER_CONTACT_ADDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string PORTAL_FOOTER_CONTACTUS {
            get {
                return ResourceManager.GetString("PORTAL_FOOTER_CONTACTUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donates.
        /// </summary>
        public static string PORTAL_FOOTER_DONATE {
            get {
                return ResourceManager.GetString("PORTAL_FOOTER_DONATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power the FEConsole Application with Your Donation!.
        /// </summary>
        public static string PORTAL_FOOTER_DONATE_DESC {
            get {
                return ResourceManager.GetString("PORTAL_FOOTER_DONATE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Here for Donation.
        /// </summary>
        public static string PORTAL_FOOTER_DONATE_LINK {
            get {
                return ResourceManager.GetString("PORTAL_FOOTER_DONATE_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string PORTAL_FOOTER_LICENSE {
            get {
                return ResourceManager.GetString("PORTAL_FOOTER_LICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LGPL.
        /// </summary>
        public static string PORTAL_FOOTER_LICENSE_DESC {
            get {
                return ResourceManager.GetString("PORTAL_FOOTER_LICENSE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where is the Beautiful.
        /// </summary>
        public static string PORTAL_IMAGE_DESC {
            get {
                return ResourceManager.GetString("PORTAL_IMAGE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMAGE.
        /// </summary>
        public static string PORTAL_IMAGE_TITLE {
            get {
                return ResourceManager.GetString("PORTAL_IMAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string PORTAL_IMG_SHOW_NEXT {
            get {
                return ResourceManager.GetString("PORTAL_IMG_SHOW_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string PORTAL_IMG_SHOW_PREV {
            get {
                return ResourceManager.GetString("PORTAL_IMG_SHOW_PREV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOKS.
        /// </summary>
        public static string PORTAL_MENU_BOOK {
            get {
                return ResourceManager.GetString("PORTAL_MENU_BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME.
        /// </summary>
        public static string PORTAL_MENU_HOME {
            get {
                return ResourceManager.GetString("PORTAL_MENU_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMAGES.
        /// </summary>
        public static string PORTAL_MENU_IMAGE {
            get {
                return ResourceManager.GetString("PORTAL_MENU_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POSTS.
        /// </summary>
        public static string PORTAL_MENU_POST {
            get {
                return ResourceManager.GetString("PORTAL_MENU_POST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share What You Believe.
        /// </summary>
        public static string PORTAL_POST_DESC {
            get {
                return ResourceManager.GetString("PORTAL_POST_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACK TO POST LIST.
        /// </summary>
        public static string PORTAL_POST_LIST {
            get {
                return ResourceManager.GetString("PORTAL_POST_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POST.
        /// </summary>
        public static string PORTAL_POST_TITLE {
            get {
                return ResourceManager.GetString("PORTAL_POST_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO!.
        /// </summary>
        public static string PORTAL_WARN_INFO {
            get {
                return ResourceManager.GetString("PORTAL_WARN_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is &lt;b&gt;NO&lt;/b&gt; Books Shared!.
        /// </summary>
        public static string PORTAL_WARN_INFO_NO_BOOKS {
            get {
                return ResourceManager.GetString("PORTAL_WARN_INFO_NO_BOOKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is &lt;b&gt;NO&lt;/b&gt; Images Shared!.
        /// </summary>
        public static string PORTAL_WARN_INFO_NO_IMAGE {
            get {
                return ResourceManager.GetString("PORTAL_WARN_INFO_NO_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is &lt;b&gt;NO&lt;/b&gt; Posts Shared!.
        /// </summary>
        public static string PORTAL_WARN_INFO_NO_POST {
            get {
                return ResourceManager.GetString("PORTAL_WARN_INFO_NO_POST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the &quot;Discovery&quot; button in Wechat, Scan the QRCode will share this content to your friends..
        /// </summary>
        public static string PORTAL_WECHAT_HELP {
            get {
                return ResourceManager.GetString("PORTAL_WECHAT_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan with Wechat to Share.
        /// </summary>
        public static string PORTAL_WECHAT_TITLE {
            get {
                return ResourceManager.GetString("PORTAL_WECHAT_TITLE", resourceCulture);
            }
        }
    }
}
